stages:
  - lint
  - infra-build
  - build
  - test
  - report
  - release

## LINT ##

# TODO: add infra/terraform linting

go_lint:
  stage: lint
  image: golang:1.14
  except:
    - mirror-config
  before_script:
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - go mod download
    - go get -u golang.org/x/lint/golint
    - golint ./...
    - go vet ./...

# TODO: add policy lint (see CasC)


## Infra build ##
# TODO: add infra build

## BUILD ##

build_go:
  stage: build
  image: golang:1.14
  except:
    - mirror-config
  before_script:
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - go build ./...

## TEST ##

unit_go:
  stage: test
  image: citihub/build:latest
  except:
    - mirror-config
  variables:
    BASE64_KUBE_CONFIG: "YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VWNVZF
TkRRWEpIWjBGM1NVSkJaMGxSUkZsMk1WZ3hTM2RKWmtSVVptbHRVR0ZLYzNWU2VrRk9RbWRyY1do
cmFVYzVkekJDUVZGelJrRkVRVTRLVFZGemQwTlJXVVJXVVZGRVJYZEthbGxVUVdkR2R6QjVUVVJC
TTAxcVJYZFBWRUV3VFdwU1lVZEJPSGxOUkZWM1RVUmplVTFVUVRWTlZGRjVUa1p2ZHdwRVZFVk1U
VUZyUjBFeFZVVkJlRTFEV1RKRmQyZG5TV2xOUVRCSFExTnhSMU5KWWpORVVVVkNRVkZWUVVFMFNV
TkVkMEYzWjJkSlMwRnZTVU5CVVVSRUNtdFVPVGwyUVdOQ05VVTFhbWxIU1RoelkxcEpUVkpvYXpS
M1RFaG1lVEowYmpJelJ6ZFROR1ZqVVVncmNEQk1ia3hpWjFkR01teHRhMmhzZDFOMFdrMEtTVTFv
TTA5TWJsUlJkRTA1UmtkNlZHUXhTSGcwY1VOWVIyOUNNMWczVFRsbVptcGpLMWxNU0V4d01tRlhV
SE0zSzJOVk5WTmtlbUYwY2xnNGNsaG1TZ3BaUlcxcUt6Wnpka0UyWlhKeU1IQXlhVXRKTmxWdU5r
ZFJXRkZIYTJocFJXNVZjVmRsY1VWMFpHMHJWRGMwTlRoeVRWa3dOVGhoUkVSSk55dE1Ua3N3Q201
RmVtVmxUMjVoT1ZsMlJHTjVSV0l5WWpVNWVVVlpjM2gzVTBreVZIRnlkRWswT1RKSVRXRm9kMHB5
UlhkalltZGFSeXRwZURKTGJ5OWpjVU5VZG1RS1IweHRRM0l5VW10RGFqVlBWbEYzTUhwWmRua3dS
Rmx4TUhwR2IybHJLMVlyUVU5dGJISlpWVU5OY0V4MFZFOWxjMFZuTjJGVGRUZEdka3RxTDJaMVR3
cEtXRlI1UmxZellrbHFhWFZWYzJoUVZVWnJSWFpGVURjM1kwUTFkRE5rWVZNeVJFaGlVbG93ZFVS
RWRIaDNaa1ZSTDFCUGFXOTJiek5JUVVaTlpITlVDalUzTlVFeFExUkxMMDQzTDJwUE5GcFRRMkZs
Y1hCTFVHSlBSak5TVDFOVVRVVXdZbVpITW5CR2RXNHpTRE52Y2tWeE1XOXZXRlpHUlhkM1IwMVpj
Mk1LY3k5b1pqazRUVmRzWmtKR2JWYzROa0l6UjJSUmFHRlFUa3BPZUdadFNrZFZValJIYlRrNVYz
aElNVlJDZDNKbmFWcEdOVEp5VG14UVNtNVROWGgwZVFwVlVGbGpiWFp1TVdWaWNGQkVPWE5rVjBa
Tk5HMHlOR1l3WTFvMk5UTktUR3BTZVM5NFN6WjJObVptYzNsamVITkhRekYyVmpWdk1sbzJja3d2
TWxsR0NtdGhXVWt6ZUhJemRtSk1ka3R5YW5sb1NtcHpOM0JMYTNndk0xbzFaMEpCYWk4emVUUlpZ
V28zTkRsa1VXSkdTbFo0WlRVeGJEbFZURFZSV1RWbWNUQUthRk5VUWxkMFRUUlFkSFp5WlRaNE5U
RXpNbGN2ZFc1R1kxaElXVk5LVG1SWE5YSnJXVzVqV25sUlNVUkJVVUZDYjNsTmQwbFVRVTlDWjA1
V1NGRTRRZ3BCWmpoRlFrRk5RMEZ4VVhkRWQxbEVWbEl3VkVGUlNDOUNRVlYzUVhkRlFpOTZRVTVD
WjJ0eGFHdHBSemwzTUVKQlVYTkdRVUZQUTBGblJVRlZlVGs0Q2taSlZtSlpTVXBHTjNWVWNrdG9S
M05zVUc1Q1NWTlJORVZsTlVWbmRGVkhaMU5zYWt4WE9ERm5jbGhLUkZCV2JXSmxOazlSTnpBNWNq
VkJZMDlLVldRS1lqUmxaVGxQVlVOeFduTlVNM1Y0ZEVObFQwNHlaRmxoTUU5Q2JWRk9hRzVHWjBw
aUsydzJVM05hVTBsUk9IbHhkV3BOYTFwQlVrNVNhUzh4V214SFNRb3lhMnd4WW0xblVWUk1XbUV2
UTA5TVpUbEllbFZxVlM5RVZ6UlJTMUZzYjFWdFFqbHViVzl6ZUdSV2FGZDVjU3R0TkhkV04zQlJP
VlEwTVRZeE9HUkxDbU5oVmtwc1oxQk9iSGNyUVZkQmMwMDVOWGhxYkhFeFYzb3JVemgxTDBnelVH
NHJhbFZaYzBWeWRWQmFiSG81Y25KV05FWnBZM1p1YkVOM2JsUk9VMmtLSzNaWVdUaHpRWFJpT1cw
elFqVjBPRFpCTVVoRmJVTlNUbVY0U200NGMyeG5TaTloWlVoNGNURklRVzV5U21acWQwcERia0pV
WjAweE1tSnhSbnBVU0FwTVozRmFNMHBYZVZSeWRIRkNlV2RKWjJOT0sxUnhTamhaYWtkdVNrODFh
bkJQU1dSaE1XWkdaRE5ZWTJaYWVWUllkM2Q0YjBSVmNUaFBiR2RRVFVKRUNqaE5XRkpZUzJWbGEx
WlFUWGhHUkZKWmJEVnhORVExUTJOdmJqSldWM2hTYjJoM2FqbEllamRKYmtObVYwZHdURk5ZUlRC
M1duSkRjMjVUWml0UWMyRUtURmRaVUdGR1dGWnlRMDE0ZDFCSWFreFZOMnBqWlZNd2FURTRTMjFI
ZGxKblVsTmpheTkzZGtjclNsVm5XRVJpZVVFdmNuRkZkbTFpT0RObVdUbFlUQXBwSzBzck16WkxR
a1pzUlVKVWVuQkdZa1FyZVhSUU5uWlVWWFJpT0RkMlFUbHJjbkI0WVdORU0yOTRSSGhLVlhSM1Vt
UnFUMEk0YURNMmFXOXRVbWxEQ2l0eFZWQmlkR3h4V1dGQlRXaGFlbGhPZUVGTmNVcFZObTVIWTBo
SGFGWm9RVk5yV0hwNk1YWjJWamRPVGprM1pFTTNObmt4T0dwSk1VZEtjR05xUlRBS1dFSXZRVlZD
YVZkelExVmpOakU1Y3pKeE1YbGtlVlZpWVVWcmFqQlNiekpXYUZVdmRUbEpQUW90TFMwdExVVk9S
Q0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CiAgICBzZXJ2ZXI6IGh0dHBzOi8vdGVzdGNsdXN0
ZXItZG5zLWQzMmUwY2Q2LmhjcC53ZXN0ZXVyb3BlLmF6bWs4cy5pbzo0NDMKICBuYW1lOiBUZXN0
Q2x1c3RlcgotIGNsdXN0ZXI6CiAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHk6IEM6XFVzZXJzXGRh
YWFkXC5taW5pa3ViZVxjYS5jcnQKICAgIHNlcnZlcjogaHR0cHM6Ly8xOTIuMTY4Ljk5LjEwMDo4
NDQzCiAgbmFtZTogbWluaWt1YmUKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IFRl
c3RDbHVzdGVyCiAgICB1c2VyOiBjbHVzdGVyVXNlcl9ha3NfdGVzdF9yZ19UZXN0Q2x1c3Rlcgog
IG5hbWU6IFRlc3RDbHVzdGVyCi0gY29udGV4dDoKICAgIGNsdXN0ZXI6IG1pbmlrdWJlCiAgICB1
c2VyOiBtaW5pa3ViZQogIG5hbWU6IG1pbmlrdWJlCmN1cnJlbnQtY29udGV4dDogVGVzdENsdXN0
ZXIKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiBjbHVzdGVyVXNl
cl9ha3NfdGVzdF9yZ19UZXN0Q2x1c3RlcgogIHVzZXI6CiAgICBjbGllbnQtY2VydGlmaWNhdGUt
ZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVVXZWRU5EUVhW
WFowRjNTVUpCWjBsU1FVbDFRM0kwTUhSdmRqQnVjRFZvZVcxWGFGaG1SRWwzUkZGWlNrdHZXa2xv
ZG1OT1FWRkZURUpSUVhjS1JGUkZURTFCYTBkQk1WVkZRWGhOUTFreVJYZElhR05PVFdwQmQwNTZT
WGhOUkd0M1RrUkpNRmRvWTA1TmFrbDNUbnBKZUUxRWEzaE9SRWt3VjJwQmR3cE5VbU4zUmxGWlJG
WlJVVXRGZHpWNlpWaE9NRnBYTURaaVYwWjZaRWRXZVdONlJWWk5RazFIUVRGVlJVRjRUVTFpVjBa
NlpFZFdlVmt5ZUhCYVZ6VXdDazFKU1VOSmFrRk9RbWRyY1docmFVYzVkekJDUVZGRlJrRkJUME5C
WnpoQlRVbEpRME5uUzBOQlowVkJNSE12VFhwT09XYzJWVVY0ZDBOWE1IZFBhV01LU0RCVFRqaE1O
MFZ5VkVwU1dIbEdiVE55V1RWb09YUmthSFExUjNsR1pucFpaM1owWkcwNWJYUk9ObXhuWldWUFlV
ZExVR1IyWWxneWRuRklOVVJaUkFwcVJHVTBTMHBLT0dOd016ZGxXbEk1VEdkQlJrMTNhazQwTmtK
MFQwTkRiVlU1SzNGdFZFbFBaRWg0ZGtObFdHMVBkR2xRTnpWaFdYVmtaM05SVnpKWENsZHNXV280
ZW1jMU5EZzFPV2hqVFhkcWVuRnBPR2RTY1RoeU4xWlJWWE5NU0ZCWFpEQnZaemcyTkZGV2RtRnFZ
a0ZOWmtaWWJGcElkMlZpYUdWTFIwc0tOM1ZRWlRrMlIwVTRNbWRhY21ORlEyMHhWbGxIV0dsT1Ns
UjBlVVp3V1dkVFREVkRNVFV2VWtsYU9YRm1abTQ0Y21KeFpUVXhOVGRYU1VneUt6aEVjQXB2T1ZG
TE4waHpibEkzUTNWUkx6UkVUSGQ2U0U5SVNYUnhhamgyY1VKUVdsbDFibFoyWlZSTk9IRmxiV3R4
TTBSV1l6UkJVbWRNVVRoT2RHSklVRFJzQ25SMFZWQXJaVXRMYWpSTmRDOVlNRVZCVG5weloyZE1j
M1J2TTIxTE1GcEtPVmh4V1ZGV05tRTNVV2xRYkZVMmVWSXZURzEwTUV0WFJHTkRTMjF4TkhjS1Jr
bHZkRkZwVWtrdlMzSjNiMmw1VUhSUVJIZzBhMDgwY0hOVmFEVmxha0ZuYWpWUWFXc3ZkemxqZFRS
U1RrUkxlVUVyTmtaS1dYZFJRMDlTVlZGQlN3cERMemMwTjFoelYxazVXbUkyUlRaMFUwTmxNRlJD
TjIxVFJGTlJjbkp3U1dkTlJHOVZUbEZhU2tnMlZqa3JUMFJoUjFneVIzTlNTVzlVU21kalRXWktD
bk5rVlhKSVMwaFhLMnhsY0RFd05FUmljVVpIWWpjd2JHWjFUMk0zYlU1dFpUTnFSMVp3WTBjclFs
RkpSRXd5ZUZnMGIyOW5LMU5NWW1WR2VFeGhjRmdLZVdsT1ZrTmpjQzh6YkZaMGVucFRVRVI1VkhK
MVZHTmtWaTkyYW14b2NVWkRkMDR4ZVhoS04yWnpNa1UxYVRaSmRFeE9XVk5yYmprMloycHJkMUZN
TlFwUGJrUTBNR1p2UjNJNGMwTkZVM0paV1RsT2NHSXJPRU5CZDBWQlFXRk5NVTFFVFhkRVoxbEVW
bEl3VUVGUlNDOUNRVkZFUVdkWFowMUNUVWRCTVZWa0NrcFJVVTFOUVc5SFEwTnpSMEZSVlVaQ2Qw
MURUVUYzUjBFeFZXUkZkMFZDTDNkUlEwMUJRWGRFVVZsS1MyOWFTV2gyWTA1QlVVVk1RbEZCUkdk
blNVSUtRVVJpV0ROalVHOUZaakY0UzBsaVFYSjJTbWxFWTJFMlVVcGpVblZRWTJac0syWXpObUZ2
YW5JeVExZDVkRTVPTTB4M1kxUTFUV3RCWjFOamJXazVkZ3B5U1VwTGJqQTFTWEprYlcxMlYwNWlP
R2cyYVdSU1JHeFVUVGhEZUVOeGNrRkhWU3RGUkZkWlIwOWhURTlpVUdOTldISnNZbVpqVkhCbGRX
cFVSa0ZPQ21WclQxUXhSM2MxVmtjMk4yNVJhbVV3UVVVNVZYTjRSbUp5WVhKdldWVlhVM293T1hC
eksyZ3ZjbU53WXk5U1dURTJSbTFoWm5WcmRWRlFPVmxIUmpJS1VsaFNTSEl5WVU4NFdDOUNRbEUw
YmxaSlNWbGFRV0p1V1ZGNFYxSXpTVVpwYjNSbWFFWXpkaXQ0YkVWSk9GUkJXbk50VW05aVZUVjBX
akF5TTNCaVJncE5TV296U1RkQk9VRldLMmR1V2xCaGFrbzBNRkVyVDAwd1ltTkNlRGR4WkVOS1Nr
Z3JOeTlyWVRnMGFrVjRZUzgwYW1SYVlVSkdURWMwWlRjMmFrNHZDbmQ1V0UxcEwwUlBPREZKVW1o
cmIyZFpjalJRYm5FeVRrMDNaMk4wT0dsc1ZYTXZhemhxYXpjeVREQnpTbFkyU0ZSM1prMXBTVWMw
WlZWUlRucHpMM29LT0hCaU1XcHNTRTQwY1RSdVRVczRRMngyVG01Qk1XbDNZVTlHUms1U1oybE9k
VEUyY1M5eFprZFZkSFExZFhsNlNWcHNWVFZHWTFSMWVXUXlORUZvVlFwNWFuWm9RM2hSUkNzMVdE
bFlLM2RoWm5wTFNYQXJOSGxxWlZJdlFuQklPVXRHYjBsRFdFNXdlalZaZFVKcE1HaE5UMHd4V0dW
MlFUaGFaVlZ0UVM5MUNsQXJNV3RqUnpjNFduaFBTVFpTU1RZM2F6ZGtPRGx6T0VaMlN6Rmxabk5G
VGpBemFrZ3lkRGxOT0M5cmFFVnVWV3hKWkhwcllXZE1PVXRGVHpRNVFtMEtWVXByTVd4RE9VOW9W
a1I0V1M5RGJWTkhlbGx2UnpWeVFXUkxhQ3RaTkhSV1ZEaHJaR05tWTNRMlluWk1WVzFoWlc1RmEy
SnhaMGxTV2taU2EzUkVVZ281TlM5RU5qZDRXbGczUW5OVWVuWkpXbkpyZEcxSFRUaHlhMHhrYW1k
VGNWZzJMMHBoUldKMmVFVXpOZ290TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09
CiAgICBjbGllbnQta2V5LWRhdGE6IExTMHRMUzFDUlVkSlRpQlNVMEVnVUZKSlZrRlVSU0JMUlZr
dExTMHRMUXBOU1VsS1MxRkpRa0ZCUzBOQlowVkJNSE12VFhwT09XYzJWVVY0ZDBOWE1IZFBhV05J
TUZOT09FdzNSWEpVU2xKWWVVWnRNM0paTldnNWRHUm9kRFZIQ25sR1pucFpaM1owWkcwNWJYUk9O
bXhuWldWUFlVZExVR1IyWWxneWRuRklOVVJaUkdwRVpUUkxTa280WTNBek4yVmFVamxNWjBGR1RY
ZHFUalEyUW5RS1QwTkRiVlU1SzNGdFZFbFBaRWg0ZGtObFdHMVBkR2xRTnpWaFdYVmtaM05SVnpK
WFYyeFphamg2WnpVME9EVTVhR05OZDJwNmNXazRaMUp4T0hJM1ZncFJWWE5NU0ZCWFpEQnZaemcy
TkZGV2RtRnFZa0ZOWmtaWWJGcElkMlZpYUdWTFIwczNkVkJsT1RaSFJUZ3laMXB5WTBWRGJURldX
VWRZYVU1S1ZIUjVDa1p3V1dkVFREVkRNVFV2VWtsYU9YRm1abTQ0Y21KeFpUVXhOVGRYU1VneUt6
aEVjRzg1VVVzM1NITnVVamREZFZFdk5FUk1kM3BJVDBoSmRIRnFPSFlLY1VKUVdsbDFibFoyWlZS
Tk9IRmxiV3R4TTBSV1l6UkJVbWRNVVRoT2RHSklVRFJzZEhSVlVDdGxTMHRxTkUxMEwxZ3dSVUZP
ZW5ObloweHpkRzh6YlFwTE1GcEtPVmh4V1ZGV05tRTNVV2xRYkZVMmVWSXZURzEwTUV0WFJHTkRT
MjF4TkhkR1NXOTBVV2xTU1M5TGNuZHZhWGxRZEZCRWVEUnJUelJ3YzFWb0NqVmxha0ZuYWpWUWFX
c3ZkemxqZFRSU1RrUkxlVUVyTmtaS1dYZFJRMDlTVlZGQlMwTXZOelEzV0hOWFdUbGFZalpGTm5S
VFEyVXdWRUkzYlZORVUxRUtjbkp3U1dkTlJHOVZUbEZhU2tnMlZqa3JUMFJoUjFneVIzTlNTVzlV
U21kalRXWktjMlJWY2toTFNGY3JiR1Z3TVRBMFJHSnhSa2RpTnpCc1puVlBZd28zYlU1dFpUTnFS
MVp3WTBjclFsRkpSRXd5ZUZnMGIyOW5LMU5NWW1WR2VFeGhjRmg1YVU1V1EyTndMek5zVm5SNmVs
TlFSSGxVY25WVVkyUldMM1pxQ214b2NVWkRkMDR4ZVhoS04yWnpNa1UxYVRaSmRFeE9XVk5yYmpr
MloycHJkMUZNTlU5dVJEUXdabTlIY2poelEwVlRjbGxaT1U1d1lpczRRMEYzUlVFS1FWRkxRMEZt
T1RaemJtVkJlRzlMYUZGR1F6Qm9WREoyUTJKUVZXWjRTV1ZFVDNCeU5Ea3hOR2RRYUdWd04wUlZX
V1JyVG5Cc1IwMVRZVkpsWWtwTVNncFlRVEZ5VDBOelkyTkxiSGxHSzNSdlZXdE9VVTFKUkc1VmIy
a3JSVGRCWWpkVFlVSnFNMGhQVlZvMlMwb3phbVpQTUVOaFR6aFdWalZoY25CS2ExVnJDalZRTWtW
NmRXWlNNbll3YkZGMVlVUnFRMDVaUWpOdE5tMTNNMjVvYW5SdFZrWk9aRkU1U0V4RFRrRTJhazlh
U2pscmFFcEJUV3RsVGpRNVFWTTNVMUFLTVV4MVoxZEZRbEJKZG1oVlpTOUdhamwwVUU1Q05WRjZi
MlJKTjA5SFYwNTFNMU50VG5aRE4wMUtkRlI2Vm1nMVpYSkRjaXQxTVhOT0wxTlRXV2x4UmdwV1dE
bHFSVzFZYnpkS1kydG9ibTR5VFVGbFlXWkJjRVZtVVU0dlZuVnpSWFZMYTJ0RlRFWmpORmh5TkRV
elkwMVpNbWQzY25CWlQxQllPVXBGZEVKVkNuUmtZVlJhVVVOUFdIQlNVMWhLVUUxTE9XUjNWMFIx
ZG5CRWVFOUllRUpUTVdOcmFHMDRaa0ZUV1UwcmVuQjVhbmM0YURaaGFXOXBialpHVTJKaVVuWUtk
MFpRVjFWV1lVa3dPRU5vZVc5Rk1tMWFSbTR3Y1d0VVNsazRXakF4ZDNsRGMwRlFhMGRrWkhrNU9U
WnZlV1V4VHk5dk9VdGtaRkJHWlZST2VXa3lkd3BRZUdWM1oyRXlTV2gzY0dGdlZXVnFhVmxVYWxO
bU0wbHJTblJMZW10UFZVMUNiMGQyYzNSaVdHeFZhazEzTlZOTFJqZHRiMEZyUkhGdE9IQjFVR1JK
Q2pkT09FNHlja2MzVnpabmVYSlFVazlhZUVFeVJIRkxaRlZTTW5kWE1rNXhVM1ZMY0VscWNWSmtk
MUZOZFhSdGRrVllOVXhNV0VoV2EweFZTWFZqYW13S1JteG1WbEpXV25CYVlXb3pRVUp2TDJOd09Y
Qk5SelpaU1hvelVsSjJRMFpaU25oeGQwRklXRlJSVlhodWFtbzRUMU0yVG1oSVNGSjVXazB6Ykhv
NFN3b3hiWGxVWVRsVWRVMVBlVUpLUW14dFMyOU9jMjVqVURaUE5FTlhMelJUYTNKYWJIQlZNMFZE
Y0UxMmNuRkNXR2hCYjBsQ1FWRkVlSHBwZG5jcmRrRmxDbTVKUWtGaGVVaGthV0l6Y2tOamRrVTVl
SE5UVm5Sc1ZpOVZNSEZsZUZKb1RVNW5SRGh3VmsweVpIaE9TbUpyZEZkb09FVkhiMDVGYlVWNFdr
NTZWbEVLUVU5NlpYRTFWblZ5Y0ZOcFFXOXRVREJ0SzNKMFNFUnpjamMwU0RsQlVEVjBaMEZ4ZGxC
T2JtZFBjakp4ZWtWMGEwdEhXVGxyTHpoTFpraEhVRlZ2V2dwdE0wVlBNRWh2T1ZOR1NIcEhVREEz
Uml0WlIzSXhkR1ExVDJKelowVkxTRzVqTHpFMlVEbFROVzVxVTBsTlVpdGhVbEY1YVVScU1HSnBX
SFJ1Y1RWaENreEphRVpYWm1kMmRsRXZkak4yV1VGUGVuRjZkVFF6T1dvNFkwbEdOR2xqY25kR1Nr
TnBkemxOT1RZeGFVTmtjVk50WjJwb1RWaEtabEEwUzNCb05YTUtRamRQWTJKTk1IcGhaamRhV1Zs
Nk1uSnZhbkYwY2xScmFsVjNOM2xRY0dkNGJVcHpUVFpRZURkaVNESlJLMHhSWWpkdWRWaDRUMUJh
WmpkS01YRk5UQXBDWm1ndlFWbFRTWE5xTmk5QmIwbENRVkZFWmt3NWRtTjNXVWRDTjJGYVlrVm1S
bGtyVkVadU5sWTVSeXRITVZsaWRXZ3ZibkE0TjFwMk9GQXpPVzh6Q2xjd1NVcGtNVGhVUW1OM2Np
OVNNUzkzY1hkYU1XcGFhMFV4U0Rkd1JISTFVM0o1ZVM4M1VVMTRiblF5WkdseVJXSnFSRW8zUlhG
NFN6TkhiV0pNYTJjS2VHUXJTVTVWVHpGc1dVcHViWHBGUjAxVVFXbG1NRzR5Y2pNNVpXdEROMUJC
UVZBM1VsVnFWMkpRYnpZemMxaElZMlY0Y2xsbFdFd3hjMVUyWVVsME9RcFJaRk1yYmtsNU0wZHpa
bWMxY2paYVNqZEVSRnBpYzJWUGFHaHdOamhtVlVoWGEybHlURFYzVFZWMVdqZzNhbE13VjI5d1JH
WndUbEJQVFN0WE1EZHlDa1pKYmt0Uk1FTlhWVzh3TjFOWlIwdHBkVGRZY25sb2NIUTNNbE4zTldK
R1EzaEtNVVpwY2lzNGVXaFJlbmh4U1dWSGQzSXlNa1k0YW1KdWVuaHZRa2tLYlVwb1owdG9hVFk1
ZERORVZFZ3lhVmxqU21WNk5VNUlNSGcwVUZKWFdGaElPR2QwWmpCeVVrRnZTVUpCVVVOQlNqVk5i
VmgyYWxGWlNWZG5ibkZqVHdwTlUybFZNekZaSzBJdlJYcEpVa05FUVVsTVlsWjFkMUZNYzBSMVNu
RXhNbFUyYW5OM2JXVkpXRGxGT0dKWmFsRXpRamR4TUdSWVVteDNkbnBZSzBWT0NrUnFNemhPTTJk
Tk16WXdUSGhrUW5KM1UwUnZUMmt5TlU1UWNWWnlRbk5qTm1wcFpHb3hSemRKYjBwcEwxaHBZVE4x
WjJrNWRYcEZPRnAwVlVSTE5HTUtkVXN5YlU0NFNrOW9XRmxIWVZBek1XNDFSemhIY1ZsdlJtb3pX
SGxUY3pWR2NXeEhVazVQWmxrM1YzVnhiaTh4U0VWUVFqQnRNelZ2VFhsQldsSlRhUXA1U1UxbU1F
Z3hNREZsT1dkMmNrTmphVWt3YkM5elRVdDBOek52Y0dodFdWQnNkREIyY25GV1NFOWFaMjVOWm5V
MUt6UkZWM1JMV1RCMVVXZHlXa1k0Q2tKR2RISm1jMWxzU0RRck1WSnBlRTVVV1ROMmVXRTNXbWcw
Y3pKaFdrRnJZM0ZRTVV4NmJWRXlkMWxwUkdkWWFEVkdOMHhRY0ZObVJGRlZUVEo0VFZJS1JqbGpi
RUZ2U1VKQlVVUkxSVTlQU0U0Mk9GRlBiVU5sU0ZZeVkyZ3lha04zY0dsbVoySmFSMFpaZG5OV01t
MXJPVE5vUVVsQ1ZFdG1OVmxJVTJkMFRBcENjbTB5Y21WRGVWWnJaRWt3VW1aSVpsaExRbGRWZVVo
bVlraG5aMllyTm1aVk1EQnJTVWhvTDBReWVEUXpkM2RqWW5abmVVcHFTRFJxTm1saVJUaFZDa3hR
ZFRJek9YWXZNV3BNVmxkT1pGaFFPR05oYWpSSVFuRnBjbmR4VDJKelRrSm9UbWx1YjFsUE56SnVO
M2xsUm1GTWNVTlRhbkpaVDJWNmNXTnZVVFFLUmpCblYwSXZUbE5oU1haNVRFd3lMeTlUYzNwWmRW
RXhNa1JpYVhwUVJsTldSamd4VlVkTWNXY3JNRkZ3U0ZsVmVtVmhWVUV3YTNSTWVHZGthSE4zU1Fw
RVZTdFBLMDV6VHpKM1EzQlRRVEZZZDJGSmFVdFlSSE5xZW5sNmR6RkdSVXRHVVRnM1dGVkNWRGN6
YmpaNVUxWkNlQzkyV2tzeWNXcElWMUYzZVhoSENuZGtSUzk1TlZsSWJWZHFTVkJFYTBaRk1VRnZN
VlpWUWpoMVZtbDNPV1Y0UVc5SlFrRlJRMEoyT1VocmJtZHlZM0p2TUZwQlRtOWhhVE4xTWtWM2FI
UUtWR0ZuTlZSRFJ6VmtRMWhZWWxwa1FqWnZlRkJoVEdob05uQnZhbE50VXk5a1UwWkVNa3hHV0hZ
dmVpOVlPVTFxYlhGUGJVaHVZVTF3ZERjclVqbEtVd3BIVm1VMFdqaFJiMFpvTlVOaVVsaGFXSEJK
VW5kNWR6VlNTRFprWmxGR04ybElaRE5VYkdSdWQyeEdOV1JxY2k5M1FXWTNRelZVZWpkMU5sRnJN
eXRSQ2xnM2NUSk5NaXRVVUZVNWEyVmFkbXN2ZDNkWWNGZFlOVVJIZDJ4aWJEWm5ORUYyVkdVeFNs
SnVNM1pQYkd4WlQwZHNNbTFJZVZoUGQwOTJWRmg2S3pRS1YyWktheTlZUmtFelprczNRVkkxT0M4
ck1GUkJURlYzTVc1TEsyOUNWak5NZVc1M2RFMXhkelF6UkVoeVJtNTJNRUZ6Tm01bGJITlBaMmRa
VVVwVGRncFlWR3R0T0hWaFVsbzJhMFJtTkhKcWRWcHZNVGczY21adFRqWmlSbkIyVDJnelNVdzRa
MFZRTWpKTFNIcEJOa00wSzA1VWRtTnBURVJOV0dJS0xTMHRMUzFGVGtRZ1VsTkJJRkJTU1ZaQlZF
VWdTMFZaTFMwdExTMEsKICAgIHRva2VuOiA0ZDk0MDg3N2U0M2M2YmVmZGM3YmRmZTllMzFlMzBj
OTZkMmY5ZDQwMzdkNjhjNTY4YzRjMzY3ZWI0ZmQ1MWIyOTk1YjlkM2UyOTFkMjEyYTU1ZGM3Nzg1
MzA0ZmIxYzJhYjU5ZWNmMGZlOTkzOTc4YzE4NmJiZjNiYzAzYjQxNwotIG5hbWU6IG1pbmlrdWJl
CiAgdXNlcjoKICAgIGNsaWVudC1jZXJ0aWZpY2F0ZTogQzpcVXNlcnNcZGFhYWRcLm1pbmlrdWJl
XHByb2ZpbGVzXG1pbmlrdWJlXGNsaWVudC5jcnQKICAgIGNsaWVudC1rZXk6IEM6XFVzZXJzXGRh
YWFkXC5taW5pa3ViZVxwcm9maWxlc1xtaW5pa3ViZVxjbGllbnQua2V5Cg=="
  before_script:
    - export TEST_KUBE_CONFIG=/tmp/test-config;
    - base64 -d $BASE64_KUBE_CONFIG > $TEST_KUBE_CONFIG;
    - cat $TEST_KUBE_CONFIG
  script:
    - cd $CI_PROJECT_DIR/test
    - go test -v ./...

# TODO: run feature/BDD (all CSPs)

## REPORT ##
# TODO

## RELEASE ##
# TODO