stages:
  - lint
  - infra-build
  - build
  - test
  - report
  - release

## LINT ##

# TODO: add infra/terraform linting

go_lint:
  stage: lint
  image: golang:1.14
  except:
    - mirror-config
  before_script:
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - go mod download
    - go get -u golang.org/x/lint/golint
    - golint ./...
    - go vet ./...

# TODO: add policy lint (see CasC)


## Infra build ##
# TODO: add infra build

## BUILD ##

build_go:
  stage: build
  image: golang:1.14
  except:
    - mirror-config
  before_script:
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - go build ./...

## TEST ##

unit_go:
  stage: test
  image: citihub/build:latest
  except:
    - mirror-config  
  script:
    - cd $CI_PROJECT_DIR/test
    - go test -v ./...

# TODO: run feature/BDD (all CSPs)

## REPORT ##
# TODO

## RELEASE ##
# TODO