apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels: 
    caller: {{ probr-caller-function }}
    feature: k-psp-005
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:  
  securityContext:
    runAsUser: 1000    
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [ 1 ]    
  containers:
  - name: psp-azp-privileges
    image: {{ probr-compatible-image }}
    command: [ "sh", "-c", "touch /tmp/healthy; sleep 1h" ]
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    securityContext:
      allowPrivilegeEscalation: {{ allowPrivilegeEscalation }}
      capabilities:
        drop: [ {{ probr-cap-drop }} ]