apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels:
    caller: {{ probr-caller-function }}
    feature: k-psp-010
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [ 1 ]
  volumes:
   - name: pvc
     persistentVolumeClaim:
       claimName: probr-pvc-test
  containers:
  - name: psp-azp-volumetypes-pvc
    image: {{ probr-compatible-image }}
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: pvc
      mountPath: /tmp/test
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ {{ probr-cap-drop }} ]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: probr-pvc-test
  labels:
    caller: {{ probr-caller-function }}
    feature: k-psp-010
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: probr-pvc-test
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
