# Empty and omitted keys will use default values
AuditEnabled: true
AuditDir: audit_output
CucumberDir: cucumber_output
OverwriteHistoricalAudits: true
ServicePacks:
  Kubernetes:
    KubeConfig: 
    KubeContext:
    AuthorisedContainerRegistry: citihubprod.azurecr.io # required
    ProbeImage: citihub/probr-probe
  # Storage:
      # Provider: # if object OR required vars within it are omitted, pack will not be included
CloudProviders:
  Azure:
    TenantID:
    SubscriptionID:
    ClientID:
    ClientSecret:
    ManagementGroup:
    Location:
    Identity:
      DefaultNamespaceAI:
      DefaultNamespaceAIB:
Tags: # allows user to create their own string of tag inclusions and/or exclusions
TagExclusions: # allows specific controls/scenarios to be disabled via a list of tags
