openapi: '3.0.0'
info:
  version: 1.0.0
  title: Probr API
  description: API providing access to CitiHub Probr Compliance as Code

paths:
  /tests:
    get:
      description: 
        Returns all tests available in the system that user has access to
      responses:
        '200':
          description: List of applicable tests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProbrTest"
        '404':
          description: No tests found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tests/run:
    post:
      summary: Run tests based on parameters.  No params will run all tests.
      operationId: runTests
      #consumes:
       # - application/json
      requestBody:
        description: specifics of tests to be run
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProbrTestCase"
      #parameters:
      #  - in: query
      #    name: 
      responses:
        '201':
          description: submitted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProbrTestCase"
        '404':
          description: error - see details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    ProbrTest:
      allOf:
        - $ref: "#/components/schemas/ProbrTestCase"
        - properties:
            uuid:
              type: string
              description: unique reference for this test instance
            # TODO: change status to enum
            status:
              type: string
              description: current status of this test
            results:
              type: object
              description: json output of test results
    ProbrTestCase:
      allOf:
        - properties:
            uuid:
              type: string
              description: unique test case reference id
            # TODO: change category to enum
            category:
              type: string
              description: category of test (e.g. kube, etc.)
            controlobjective:
              type: string
              description: objective of this control / test case

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: error code
        message:
          type: string
          description: error message
      required:
        - code
        - message